// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0JEvY0tajPsQ2zeAlkElbInXjWNkXYv4',
    appId: '1:479348462905:web:39423290036f6f28a0c4e8',
    messagingSenderId: '479348462905',
    projectId: 'todo-app-6539f',
    authDomain: 'todo-app-6539f.firebaseapp.com',
    storageBucket: 'todo-app-6539f.appspot.com',
    measurementId: 'G-FCMYYNLW2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApEQQuh1EArGqi6j8W0tVRgbNUzXh1Wso',
    appId: '1:479348462905:android:d0e4c9fe959d1314a0c4e8',
    messagingSenderId: '479348462905',
    projectId: 'todo-app-6539f',
    storageBucket: 'todo-app-6539f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcW8WdJRN2YgRuq_eR31voQh87os5b8Y',
    appId: '1:479348462905:ios:1bca98baa8d5abf6a0c4e8',
    messagingSenderId: '479348462905',
    projectId: 'todo-app-6539f',
    storageBucket: 'todo-app-6539f.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcW8WdJRN2YgRuq_eR31voQh87os5b8Y',
    appId: '1:479348462905:ios:d6fcd1923cc580c2a0c4e8',
    messagingSenderId: '479348462905',
    projectId: 'todo-app-6539f',
    storageBucket: 'todo-app-6539f.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
